name: SYNKROAD Build CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project / Solution
      run: |
        if (Test-Path "*.sln") {
            msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
        } else {
            msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} *.vcxproj
        }